language: node_js

node_js:
  - '7'
  - '4'

addons:
  sauce_connect: true

branches:
  only:
    - master

before_script:
  - npm run build

script:
  - npm run test:node
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run test:browser; fi

after_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run coverage; fi