language: node_js

matrix:
  fast_finish: true
  include:
    - env: TEST='node'
      node_js:
        - '7'
        - '4'
    - env: TEST='browser'
      node_js: '4'
  allow_failures:
    - env: TEST='browser'

addons:
  sauce_connect: true

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: npm
  email: iegoroff@gmail.com
  api_key:
    secure: >
      PAl67IZSleqhj+2H5NGtuCXMZFKhOjrL7vrNEz0kfQQXceDTOMc8jFtiVUaNJWiP7QvowBeyNXLCgiN3ydVKbIHn39tmQQUyYpMBvyukBiamxsqOi
      iiHRbhuapQgfCX6njetoTK9fv/oZ9s1oV0+OgKlijjQVt1yJxRX87FGpLKqIg3cH5YVVx+xQnNoRkzkHvoDHxXQSJ/flZ2PDi2TyZ8fyr2ux7VW73
      7ge4bzxeH5ZnoRN2zSv6KgKMBYmrH3NRdW6dEQ1UnjRL9QetcTIUZPQPJUhMUKpDWpGEdsxvVxLW9st4zdkggVnfMozR3fKNv+yrBXtztPXq1Iw/B
      kPfW9cEZg8F23u3WSE5xdjhT235nObeXZpWkYqx5Zpel+aJnNoNc9XrzaeiCddKzdW3eIwv+NOwL/QG7fbiDFUT5Nch9h9z6/Wg3KuRCYtn8knAnV
      Mvvw4j6yMxMS69b2WGoZNY+JkuxZV7eOdGeHb/tGFFPQ8jXpparHxux5PWNN22bsk5ybX9nJbjTgiuRhgZbPE54UvzKOz9ewV3jvUVBFTSVc97bBL
      8pv+4XZTu3jE7yV1KyAkAite2aLeToEt10GQhKI+0ZGJxtt25GggaDEqjR5Gr8aHcbX0j2nU5cIxXciUIfbuxS7ap8xJNNkztfTVBHd8nsmsmkChU
      3hSVY=
  on:
    tags: true
    condition: $TEST == 'node'


before_script:
  - npm run build

script:
  - if [[ $TEST == 'node' ]]; then npm run lint && npm run test:node; fi
  - if [[ $TEST == 'browser' ]]; then npm run test:browser; fi
after_script:
  - if [[ $TEST == 'node' ]]; then npm run coverage; fi